# Generated by Django 4.2.5 on 2023-09-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
