# Generated by Django 4.2.5 on 2023-09-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='remark',
        ),
        migrations.AddField(
            model_name='cart',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
