# Generated by Django 4.2.5 on 2023-09-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_name_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
