# Generated by Django 4.2.5 on 2023-09-16 08:07

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sub_image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='說明(黑字)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='說明(綠字)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='說明(藍字)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='說明(紅字)'),
        ),
    ]
