# Generated by Django 4.2.5 on 2023-09-16 08:09

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_product_sub_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path, verbose_name='主要圖片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sub_image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path, verbose_name='次要圖片'),
        ),
    ]
