# Generated by Django 4.2.5 on 2023-09-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_country_alter_order_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(default='https://res.cloudinary.com/dp53ha8ie/image/upload/v1689443351/test/akgsqjsp0h0dtbb2v4en.png', max_length=250, verbose_name='圖片網址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(max_length=250, verbose_name='主圖網址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sub_image',
            field=models.CharField(default='https://res.cloudinary.com/dp53ha8ie/image/upload/v1689443351/test/akgsqjsp0h0dtbb2v4en.png', max_length=250, verbose_name='次圖網址'),
            preserve_default=False,
        ),
    ]
