# Generated by Django 4.2.5 on 2023-09-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=500, verbose_name='圖片網址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='主圖網址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sub_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='次圖網址'),
        ),
    ]
