# Generated by Django 4.2.5 on 2023-09-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_category_image_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lname',
        ),
    ]
