# Generated by Django 4.2.5 on 2023-09-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_order_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
