# Generated by Django 4.2.5 on 2023-09-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_order_state_remove_profile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
