# Generated by Django 4.2.5 on 2023-09-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_order_country_remove_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='single_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
