# Generated by Django 4.2.5 on 2023-09-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_order_single_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='single_price',
        ),
    ]
