# Generated by Django 4.2.5 on 2023-10-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_order_single_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uniNumber',
            field=models.CharField(default='6677889933', max_length=10),
            preserve_default=False,
        ),
    ]
