# Generated by Django 4.2.5 on 2023-10-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_profile_uninumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uniNumber',
            field=models.CharField(default='11223344', max_length=10),
            preserve_default=False,
        ),
    ]
